# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'goldtime' do

  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]
   # React Native third party dependencies podspecs
   pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
   pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
   pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  
  pod 'GoogleSignIn'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'



  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'react-native-video', :path => '../node_modules/react-native-video'

  pod 'react-native-orientation', :path => '../node_modules/react-native-orientation'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'RNAudio', :path => '../node_modules/react-native-audio'

  pod 'react-native-track-player', :path => '../node_modules/react-native-track-player'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
